version: '3.4'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always      
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: Test_schema
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: mysqleight
      MYSQL_PASSWORD: mysqleight
  nodejslearning:
    depends_on:
      - db
    image: nodejslearning
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000