version: '3.4'

services:
  nodejslearning:
    image: nodejslearning
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - "./app:/usr/src/app/app"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"        
    environment:
      MYSQL_DATABASE: Test_schema
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: mysqleight
      MYSQL_PASSWORD: mysqleight
      MYSQL_ROOT_HOST: localhost
  backend:
    depends_on:
      - db
    build: ./backend
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - "8080:8080"